apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
spec:
  replicas: 1
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - image: okteto.dev/was:latest
        name: was
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "33adae69-76f3-4f47-a6d3-9fc127a916ea"
        - name: Vless_Path
          value: "/vfhyk6756hr44tgrd"
        - name: Vmess_UUID
          value: "33adae69-76f3-4f47-a6d3-9fc127a916ea"
        - name: Vmess_Path
          value: "/fdg56u45ytyj89i7f"
        - name: Share_Path
          value: "/v2link"
